common-desktop-apps:
  pkg.installed:
    - pkgs:
      - bolt
      - chromium
      - curl
      - feh
      - firefox-esr
      - gimp
      - gmrun
      - inkscape
      - keepassxc
      - mesa-utils
      - simple-scan
      - terminator
      - thunderbolt-tools
      - totem
      - yubikey-personalization
      - wcalc
      - wireshark
      - zathura
      - zenity
