# Base Image
ARG TEST_IMAGE=docker.io/debian:12
FROM ${TEST_IMAGE} AS base

# Update OS Software
RUN apt-get update && apt full-upgrade -y

# Install Test Dependencies
RUN apt-get install -y systemd python3-testinfra

# Pre-install Desktop Packages (allows moving big things into the OCI image)
RUN apt-get install -y build-essential python3-dev python3-venv cinnamon-core \
    firefox-esr chromium thunderbird gimp inkscape libreoffice-writer x11-apps \
    vim vlc git openssh-client wget totem wireshark keepassxc fonts-pc evince   \
    apparmor exim4-daemon-light xserver-xorg-core xwayland kwayland-integration  \
    chrony simple-scan terminator thunderbolt-tools totem yubikey-personalization \
    && apt-get autoremove -y && apt-get clean
