# Default: Debian 13
ARG TEST_IMAGE=docker.io/debian:13

# Copy files into base image
FROM ${TEST_IMAGE} AS base

# Update sofware
RUN apt update && apt upgrade -y

# Install ansible and testing dependencies
# Note: pamtester probes a named PAM stack directly, which is how the
#       access.conf tests avoid needing a real login session.
RUN apt install -y ansible-core python3-testinfra systemd systemd-sysv kmod pamtester

# Put large static list of Desktop Packages into a cacheable layer
# - base_roles/common/tasks/packages:
RUN apt install -y anacron net-tools nftables openssl procps rsync screen tcpdump tmux tree unzip \
	whois wget locate curl pkg-config ssl-cert vim
# - conf/roles/desktop/tasks/cinnamon:
RUN apt install -y dbus-x11 libx11-data x11-apps x11-session-utils x11-xkb-utils x11-xserver-utils \
	xserver-xorg-core xserver-xorg-input-all xwayland kwayland-integration bolt chromium curl feh \
	firefox-esr gimp gmrun inkscape keepassxc mesa-utils simple-scan terminator thunderbolt-tools \
	totem yubikey-personalization wcalc wireshark zathura zenity apparmor apparmor-utils blueman \
	cinnamon-core dconf-cli eog evince firefox-esr chromium fonts-liberation fonts-pc fonts-recommended \
	gnome-calculator gnome-screenshot thunderbird totem vlc cheese cups gimp gnome-disk-utility \
	gnome-font-viewer gnome-system-monitor gnote gstreamer1.0-libav gstreamer1.0-plugins-ugly inkscape \
	laptop-mode-tools libreoffice-calc libreoffice-gnome libreoffice-impress libreoffice-writer \
	mate-themes orca remmina rhythmbox seahorse gnome-photos simple-scan sound-theme-freedesktop \
	system-config-printer zenity

# Run systemd as PID 1 so roles can start and restart services
CMD ["/sbin/init"]
