---
- name: Regular Maintenance
  hosts: localhost
  vars:
    partial_install: "{{ ansible_is_chroot }}"
    is_server: "{{ not 'pc' in ansible_hostname }}"
    is_desktop: "{{ 'pc' in ansible_hostname }}"
    is_test: "{{ 'test' in ansible_hostname }}"
  roles:
    - common
    - custom
    - cleanup
