- name: Configure apt preferences
  ansible.builtin.copy:
    src: pinning.prefs
    dest: /etc/apt/preferences.d/pinning
    mode: "0644"
  notify: refresh-apt

- name: Manage default apt sources
  ansible.builtin.template:
    src: debian.sources
    dest: /etc/apt/sources.list.d/debian.sources
    mode: "0644"
  notify: refresh-apt

- name: Remove legacy (one-line) sources
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
  notify: refresh-apt
