##
# Core Libraries and Configuration
##

- name: Shell Helpers
  ansible.builtin.copy:
    src: shell.sh
    dest: /usr/local/lib/shell
    mode: "0755"

- name: Configure gai.conf
  ansible.builtin.copy:
    src: gai.conf
    dest: /etc/gai.conf
    mode: "0644"

##
# Additional Configuration
##

- name: Install git package
  ansible.builtin.package:
    name: git
    state: present

- name: Obtain copy of teckhost configuration
  ansible.builtin.git:
    repo: https://github.com/MTecknology/teckhost.git
    dest: /etc/ansible
    version: "{{ common_gitrev }}"
    update: false  # ansible-forced updates will reset local history

- name: Remove self-managed ansible runs from cron
  ansible.builtin.cron:
    name: ansible-maintenance
    state: absent

- name: Manage self-managed ansible service
  ansible.builtin.copy:
    src: ansible-maintenance.service
    dest: /etc/systemd/system/ansible-maintenance.service
    mode: "0644"
  notify: reload-systemd

- name: Ensure self-managed ansible service is enabled
  ansible.builtin.systemd_service:
    name: ansible-maintenance.service
    enabled: true

##
# Server Includes
##

- name: Include SSH-Server for test or non-pc
  ansible.builtin.include_tasks:
    file: sshd.yml
  when: is_server or is_test
