- name: Install fail2ban package
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Manage f2b/jail.local file
  ansible.builtin.copy:
    src: f2b_jail.local
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: restart-fail2ban

- name: Ensure fail2ban service is running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when: not partial_install
