##
# NFTables
##

- name: Ensure nftables is installed
  ansible.builtin.package:
    name: nftables
    state: present

- name: Manage nftables configuration
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    mode: "0755"
  notify: reload-nft

##
# Fail2Ban
##

- name: Install fail2ban package
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Manage f2b/jail.conf file
  ansible.builtin.copy:
    src: f2b_jail.conf
    dest: /etc/fail2ban/jail.conf
    mode: "0644"
  notify: restart-fail2ban

- name: Manage f2b/jail.conf file
  ansible.builtin.copy:
    src: f2b_fail2ban.conf
    dest: /etc/fail2ban/fail2ban.conf
    mode: "0644"
  notify: restart-fail2ban

- name: Ensure f2b service is running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when: not partial_install
