- name: Install ntp package
  ansible.builtin.package:
    name: chrony
    state: present
  when: "'container' not in ansible_virtualization_tech_guest"

- name: Manage chrony.conf file
  ansible.builtin.copy:
    src: chrony.conf
    dest: "{{ common_chrony_path }}"
    mode: "0640"
  notify: restart-chrony
  when: "'container' not in ansible_virtualization_tech_guest"

- name: Ensure chrony service is running
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  when:
    - not partial_install
    - "'container' not in ansible_virtualization_tech_guest"

- name: Remove conflicting ntp implementation
  ansible.builtin.package:
    name: systemd-timesyncd
    state: absent
