- name: Restart polkit service
  listen: restart-polkit
  ansible.builtin.service:
    name: polkit
    state: restarted
  when: not partial_install

- name: Trigger "dconf update"
  listen: dconf-update
  ansible.builtin.command:
    cmd: dconf update
  register: dconf_update
  failed_when: "dconf_update.rc != 0"
  changed_when: false
