- name: Extra packages for MikePC
  ansible.builtin.package:
    name:
      - vim
      # Laptop Extras
      - claws-mail
      - claws-mail-multi-notifier
      - pylint
      - python3-pudb
      - python3-flake8
      - python3-pytest
      - python3-testinfra
      - redshift-gtk
      - syslinux
      - isolinux
      - texlive-latex-base
      - texlive-latex-recommended
      - vagrant
      - xorriso
      # - virtualbox
    state: present

- name: Check for final mikecp setup
  ansible.builtin.stat:
    path: /home/michael/repos/data/.private
  register: mikepc_firstrun

- name: Create firstlogin script for final configuration of mikepc
  ansible.builtin.copy:
    src: firstlogin_mikepc.sh
    dest: /home/michael/firstlogin
    owner: michael
    group: michael
    mode: '0750'
  when: not mikepc_firstrun.stat.exists

- name: MikePC homedir structure - P1
  ansible.builtin.file:
    path: "/home/michael/{{ dpath }}"
    state: directory
    owner: michael
    group: michael
    mode: "0755"
  with_list:
    - repos
    - .config
    - .vim
    - .vim/tmp
    - .vim/tmp/backup
    - .vim/tmp/swap
    - .vim/tmp/undo
  loop_control:
    loop_var: dpath

- name: Obtain copy of home data repository
  ansible.builtin.git:
    repo: https://github.com/MTecknology/homedata.git
    dest: /home/michael/repos/data
    update: false

- name: Set permissions on cloned repository
  ansible.builtin.file:
    path: /home/michael/repos/data
    owner: michael
    group: michael
    recurse: true

- name: MikePC homedir structure - P2
  ansible.builtin.file:
    path: "/home/michael/{{ dpath }}"
    state: directory
    owner: michael
    group: michael
    mode: "0700"
  with_list:
    - .ssh
    - .gnupg
  loop_control:
    loop_var: dpath

- name: MikePC homedir structure - P3
  ansible.builtin.file:
    state: link
    src: /home/michael/{{ dpath.target }}
    dest: "/home/michael/{{ dpath.link }}"
    force: true
    follow: false
  with_list:
    - link: .config/autostart
      target: repos/data/.homedir/.config/autostart
    - link: .config/compiz
      target: repos/data/.homedir/.config/compiz
    - link: .config/keepassxc
      target: repos/data/.homedir/.config/keepassxc/
    - link: .config/mate-menu
      target: repos/data/.homedir/.config/mate-menu/
    - link: .config/openbox
      target: repos/data/.homedir/.config/openbox/
    - link: .config/redshift.conf
      target: repos/data/.homedir/.config/redshift.conf
    - link: .config/terminator
      target: repos/data/.homedir/.config/terminator/
    - link: .config/user-dirs.dirs
      target: repos/data/.homedir/.config/user-dirs.dirs
    - link: .bash_aliases
      target: repos/data/.homedir/.bash_aliases
    - link: .bash_logout
      target: repos/data/.homedir/.bash_logout
    - link: .bashrc
      target: repos/data/.homedir/.bashrc
    - link: .bin
      target: repos/data/.private/.bin
    - link: .crypt
      target: repos/data/.private/.crypt
    - link: .dput.cf
      target: repos/data/.homedir/.dput.cf
    - link: .gbp.conf
      target: repos/data/.homedir/.gbp.conf
    - link: .gnupg/gpg.conf
      target: repos/data/.private/.gnupg/gpg.conf
    - link: .gitconfig
      target: repos/data/.homedir/.gitconfig
    - link: .pass.kdbx
      target: .crypt/mnt/vault/pass.kdbx
    - link: .pbuilderrc
      target: repos/data/.homedir/.pbuilderrc
    - link: .profile
      target: repos/data/.homedir/.profile
    - link: .quiltrc
      target: repos/data/.homedir/.quiltrc
    - link: .sbuildrc
      target: repos/data/.homedir/.sbuildrc
    - link: .screenrc
      target: repos/data/.homedir/.screenrc
    - link: .ssh/config
      target: .crypt/mnt/vault/ssh/config
    - link: .ssh/id_ed25519
      target: .crypt/mnt/vault/ssh/id_ed25519
    - link: .ssh/id_ed25519.pub
      target: .crypt/mnt/vault/ssh/id_ed25519.pub
    - link: .signature
      target: repos/data/.homedir/.signature
    - link: .vimrc
      target: repos/data/.homedir/.vimrc
    - link: .vim/ftdetect
      target: repos/data/.homedir/.vim/ftdetect
    - link: .vim/ftplugin
      target: repos/data/.homedir/.vim/ftplugin
    - link: .vim/salt-vim.spec
      target: repos/data/.homedir/.vim/salt-vim.spec
    - link: .vim/spell
      target: repos/data/.homedir/.vim/spell
    - link: .vim/syntax
      target: repos/data/.homedir/.vim/syntax
    - link: .wallpaper.png
      target: repos/data/.homedir/.wallpaper.png
  loop_control:
    loop_var: dpath
