- name: Install X packages
  ansible.builtin.package:
    name:
      - dbus-x11
      - libx11-data
      - x11-apps
      - x11-session-utils
      - x11-xkb-utils
      - x11-xserver-utils
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xwayland
      - kwayland-integration
      - firmware-misc-nonfree

- name: Install Desktop packages
  ansible.builtin.package:
    name:
      - bolt
      - chromium
      - curl
      - feh
      - firefox-esr
      - gimp
      - gmrun
      - inkscape
      - keepassxc
      - mesa-utils
      - simple-scan
      - terminator
      - thunderbolt-tools
      - totem
      - yubikey-personalization
      - wcalc
      - wireshark
      - zathura
      - zenity

- name: Manage xorg.d/dpms.conf
  ansible.builtin.copy:
    src: xorg_dpms.conf
    dest: /etc/X11/xorg.conf.d/dpms.conf
    mode: "0644"

- name: Install packages for Cinnamon Desktop
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
      - blueman
      - cinnamon-core
      - dconf-cli
      - eog
      - evince
      - firefox-esr
      - chromium
      - fonts-liberation
      - fonts-pc
      - fonts-recommended
      - fonts-ubuntu
      - gnome-calculator
      - gnome-screenshot
      - thunderbird
      - totem
      - vlc
      - cheese
      - cups
      - gimp
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-system-monitor
      - gnote
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-ugly
      - inkscape
      - laptop-mode-tools
      - libreoffice-calc
      - libreoffice-gnome
      - libreoffice-impress
      - libreoffice-writer
      - mate-themes
      - orca
      - remmina
      - rhythmbox
      - seahorse
      - gnome-photos
      - simple-scan
      - sound-theme-freedesktop
      - system-config-printer
      - zenity

- name: Remove desktop cruft
  ansible.builtin.package:
    name:
      - apache2-bin
      - gnome-games
      - gnome-software-common
      - gnome-user-share
      - hexchat
      - hexchat-common
      - hexchat-plugins
      - transmission-gtk
      - transmission-common
    state: absent

- name: Copy desktop configuration files and images
  ansible.builtin.copy:
    src: "lightdm/{{ fpath }}"
    dest: "/etc/lightdm/{{ fpath }}"
    mode: "0644"
  with_list:
    - loginbg.jpg
    - defaultbg.jpg
    - lightdm.conf
    - lightdm-gtk-greeter.conf
  loop_control:
    loop_var: fpath

- name: Configure default display manager
  ansible.builtin.copy:
    dest: /etc/X11/default-display-manager
    content: /usr/sbin/lightdm
    mode: "0644"

- name: Configure default background via alternatives
  community.general.alternatives:
    name: desktop-background
    link: /usr/share/images/desktop-base/desktop-background
    path: /etc/lightdm/defaultbg.jpg
    priority: 100
