- name: Manage signal apt key
  ansible.builtin.copy:
    src: signal-keyring.gpg
    dest: /usr/share/keyrings/signal-desktop-keyring.gpg
    mode: "0644"
  notify: refresh-apt

- name: Manage apt sources for signal
  ansible.builtin.copy:
    src: signal.sources
    dest: /etc/apt/sources.list.d/signal.sources
    mode: "0644"
  notify: refresh-apt

- name: Remove legacy format
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/signal.list
    state: absent

- name: Force apt refresh now
  ansible.builtin.meta: flush_handlers

- name: Install signal-desktop package
  ansible.builtin.package:
    name: signal-desktop
    state: present
