##
# SystemDerpies
##

- name: Reload systemd
  listen: reload-systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

##
# Misc.
##

- name: Update apt cache
  listen: refresh-apt
  ansible.builtin.apt:
    update_cache: true

- name: Trigger "update-grub"
  listen: update-grub
  ansible.builtin.command:
    cmd: update-grub
  register: update_grub
  failed_when: "update_grub.rc != 0"
  changed_when: false
  when: "'container' not in ansible_virtualization_tech_guest"

##
# Restart Services
##

- name: Restart chrony service
  listen: restart-chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
  when: not partial_install

- name: Restart fail2ban service
  listen: restart-fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: not partial_install

- name: Restart sshd service
  listen: restart-sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: not partial_install

- name: Reload nftables service
  listen: restart-nftables
  ansible.builtin.service:
    name: nftables
    # Restart destroys any temporary tables
    state: reloaded
  when: not partial_install
